### ISSUE TITLE
Device.audio.setInputDevice not working?

### ISSUE THREAD

**Issue by JunusErgin** [twilio/client-js-1.4-examples#1]
Hello Twilio engineers,

this is probably the wrong repository. I hope, you can redirect me to the right one. I'm trying to set another twilio input device in the Twilio.js 1.4 library as explained here: https://www.twilio.com/docs/api/client/device#audio
After creating an outgoing phone call, i don't get invited to the room anymore as a creator of the room.
````
Twilio.Device.ready((device: any) => {
        device.audio.setInputDevice('default').then(function() {
            console.info('Success!');
            //  ... go on with creating the room in the backend and getting `room_id`
           this._twilioPhoneClient.connect({'name': room_id}); // Does not throw an error
        });
});
````
if i remove the line `device.audio.setInputDevice('default')` everything works fine. After setting the input device and calling some phone, the phone hears a weird string music which usually means that the creator of the room is not a participant of the room.

Do you have any suggestions?

Thanks in advance,

Junus

**Comment by liberty-rowland** [comment]
Hi @JunusErgin,

To clarify, is this the flow you're describing?
1. Make a call using the above code to TwiML app
2. TwiML app calls specified phone number
3. Phone rings, and is picked up
4. The phone end hears "weird string music".


If so, could you elaborate on a few things?
1. What do you mean by "weird string music"?
2. Does the calling side hear the phone's input correctly?
3. Which browsers / OSes are you using?
4. Do you get any errors in console?

If possible, it would be a great help if you could host an example of this behavior somewhere so that I can attempt to reproduce the issue.

Thanks for the report!

**Comment by liberty-rowland** [comment]
Hey @JunusErgin 

Just checking in to see if this is still an issue. If I don't hear back in a few, I'll close out this issue.
