### ISSUE TITLE
conn.on('volume', setVolumes) works only once

### ISSUE THREAD

**Issue by mcpacific** [twilio/client-js-1.4-examples#3]
It seems to work fine the first time, but after I end the call and make another call, it doesn't work at all.

**Comment by liberty-rowland** [comment]
@mcpacific Thanks for creating the issue. Can you confirm that your expected behavior is:
1) Get an instance of `Connection` from `Device.connect(handler)`
2) Set `conn.on('volume', volumeHandler)`
3) Close the connection
4) Open a new connection
5) Don't set `conn.on('volume', volumeHandler)` on new Connection
6) Expect the handler set on previous Connection to still fire on new connection
