### ISSUE TITLE
disconnect-event is not fired when incoming call is closed before accepting

### ISSUE THREAD

**Issue by dennobaby** [twilio/client-js-1.4-examples#5]
Hi,

if incoming connections are not accepted immediately (e.g. accept per button) and the incoming call ends before accepting the call, the "disconnect"-event is not fired, though the connection-status is "closed".

I am missing here something?

**Comment by dennobaby** [comment]
Hi,

i noticed, that the same behavior happens if i call 

`connection.reject();
`
But in this time the connection-status is "pending". 

I think this is definitely a bug.

**Comment by liberty-rowland** [comment]
@dennobaby In the first case (call times out), the call is never actually connected so it does not disconnect. Instead, Twilio cancels the call. The callee should receive a `Device.on('cancel')` event.

In the second case, your application should already know you're rejecting the call (because it called `Connection.reject()`), however if you're using React or another framework where it's easier to listen for events, you can listen for `Connection.on('rejected')`.
